<?php
require 'includes/session.php';
// generate_pdf.php
require 'includes/connection.php';
require 'includes/functions.php';
require 'dompdf/autoload.inc.php';

use Dompdf\Dompdf;
use Dompdf\Options;

// Verify session and permissions
if (!isset($_SESSION['userId']) || !$_SESSION['isLogin']) {
    header("location: login.php");
    exit;
}

if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['download_pdf']) && isset($_SESSION['report_results'])) {
    $results = $_SESSION['report_results'];
    $filters = $_SESSION['report_filters'];

    ob_start();
    ?>
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <title>Enrollment Report</title>
        <style>
            body { font-family: DejaVu Sans, sans-serif; font-size: 12px; }
            .header { text-align: center; margin-bottom: 20px; }
            .report-title { font-size: 18px; font-weight: bold; }
            .report-date { font-size: 12px; color: #555; }
            table { width: 100%; border-collapse: collapse; margin-top: 15px; }
            th { background-color: #f2f2f2; font-weight: bold; }
            th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
            .footer { margin-top: 30px; font-size: 10px; text-align: right; color: #777; }
        </style>
    </head>
    <body>
        <div class="header">
            <div class="report-title">Enrollment Report</div>
            <div class="report-date">Generated: <?= date('F j, Y H:i') ?></div>
        </div>
        
        <div class="filters">
            <p><strong>Period:</strong> <?= htmlspecialchars($filters['start_date']) ?> to <?= htmlspecialchars($filters['end_date']) ?></p>
            <p><strong>Course:</strong> <?= !empty($filters['course_id']) ? htmlspecialchars(readcolumn('courses', 'Course_name', $filters['course_id'])) : 'All Courses' ?></p>
        </div>

        <table>
            <thead>
                <tr>
                    <th>#</th>
                    <th>Student</th>
                    <th>Course</th>
                    <th>Enrollment Date</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($results as $index => $r): ?>
                <tr>
                    <td><?= $index + 1 ?></td>
                    <td><?= htmlspecialchars($r['student_name']) ?></td>
                    <td><?= htmlspecialchars($r['Course_name']) ?></td>
                    <td><?= htmlspecialchars($r['enrollment_date']) ?></td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>

        <div class="footer">
            Generated by <?= htmlspecialchars($_SESSION['user_name'] ?? 'System') ?> | Total: <?= count($results) ?> records
        </div>
    </body>
    </html>
    <?php
    $html = ob_get_clean();

    $options = new Options();
    $options->set('isHtml5ParserEnabled', true);
    $options->set('defaultFont', 'DejaVu Sans');
    $options->set('isRemoteEnabled', true);

    $dompdf = new Dompdf($options);
    $dompdf->loadHtml($html);
    $dompdf->setPaper('A4', 'portrait');
    $dompdf->render();
    $dompdf->stream("Enrollment_Report_".date("Ymd_His").".pdf", ["Attachment" => true]);
    exit;
}

header("location: admin_report.php");
exit;